package misc;

public enum ViewType {
    LOGIN,
    REGISTRAZIONE,
    MAIN,
    PROFILO,
    CREA_ANNUNCIO,
    VISUALIZZA_ANNUNCI,
    VISUALIZZA_OFFERTE,
    GESTIONE_PRODOTTI,
    ORDINI,
    CONSULENZA,
    // Appuntamenti (use case futuro)
    LISTA_APPUNTAMENTI,
    DETTAGLIO_APPUNTAMENTO,
    PRENOTAZIONE,
    CANCELLAZIONE_APPUNTAMENTO
}